name: ✨ 기능 추가
description: 새로운 기능이나 개선 사항을 제안합니다.
title: '[FEATURE] '
labels: ['enhancement']
body:
  - type: textarea
    id: background
    attributes:
      label: "💡 제안 배경"
      placeholder: "왜 필요한 기능인가요?"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: "🧩 제안 내용"
      placeholder: "구체적인 기능 설명"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "🚀 기대 동작"
      placeholder: "추가 후 기대 효과"
  - type: checkboxes
    id: platforms
    attributes:
      label: "📱 적용 대상"
      options:
        - label: "Android"
        - label: "iOS"
        - label: "Common (Shared)"
  - type: checkboxes
    id: theme
    attributes:
      label: "🎨 적용 테마"
      options:
        - label: "Material3"
        - label: "Cupertino"
  - type: checkboxes
    id: module
    attributes:
      label: "💻 모듈"
      options:
        - label: "Common"
        - label: "Utilities"
        - label: "UI"
        - label: "Adaptive UI"
        - label: "Preferences"
        - label: "Navigation3"
        - label: "Firebase"
        - label: "DateTime"
        - label: "FileKit"
        - label: "Icons"
        - label: "Example"
